<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>EMSE 6035 - Syllabus</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./images/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<!-- fontawesome icons -->
<script src="https://kit.fontawesome.com/1392a7030f.js" crossorigin="anonymous"></script>




<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="EMSE 6035 - Syllabus">
<meta property="og:description" content="Course website for Fall 2026 semester of the EMSE course “Marketing Analytics for Design Decisions” at GWU">
<meta property="og:image" content="https://madd.seas.gwu.edu/2026-Fall/images/logo.png">
<meta property="og:site_name" content="https://madd.seas.gwu.edu/">
<meta property="og:locale" content="es_ES">
<meta property="og:image:height" content="1153">
<meta property="og:image:width" content="1000">
<meta name="twitter:title" content="EMSE 6035 - Syllabus">
<meta name="twitter:description" content="Course website for Fall 2026 semester of the EMSE course “Marketing Analytics for Design Decisions” at GWU">
<meta name="twitter:image" content="https://madd.seas.gwu.edu/2026-Fall/images/logo-square.png">
<meta name="twitter:creator" content="@johnhelveston">
<meta name="twitter:site" content="@johnhelveston">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./syllabus.html">Syllabus</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">EMSE 6035</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><i class="bi bi-house-door-fill" role="img">
</i> 
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./syllabus.html" class="sidebar-item-text sidebar-link active"><i class="bi bi-map-fill" role="img">
</i> 
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./schedule.html" class="sidebar-item-text sidebar-link"><i class="bi bi-table" role="img">
</i> 
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false"><i class="bi bi-pencil-square" role="img">
</i> 
 <span class="menu-text">Final Project</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./project/0-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./project/1-proposal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Proposal</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./project/2-survey-plan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Survey Plan</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./project/3-pilot-survey.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pilot Survey</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./project/4-pilot-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pilot Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./project/5-final-survey.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Final Survey</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./project/6-final-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Final Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./project/7-final-presentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Final Presentation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./project/examples.html" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-medical" role="img">
</i> 
 <span class="menu-text">Examples</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./software.html" class="sidebar-item-text sidebar-link"><i class="bi bi-download" role="img">
</i> 
 <span class="menu-text">Software</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./faq.html" class="sidebar-item-text sidebar-link"><i class="bi bi-question-square-fill" role="img">
</i> 
 <span class="menu-text">FAQ</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link"><i class="bi bi-bookmark-fill" role="img">
</i> 
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://madd.seas.gwu.edu/showcase.html#fall-2025" class="sidebar-item-text sidebar-link"><i class="bi bi-bar-chart-line-fill" role="img">
</i> 
 <span class="menu-text">Project Showcase</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://emse-madd-f26.slack.com" class="sidebar-item-text sidebar-link"><i class="bi bi-slack" role="img">
</i> 
 <span class="menu-text">Slack</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://jhelvy.appointlet.com/b/professor-helveston" class="sidebar-item-text sidebar-link"><i class="bi bi-clock-fill" role="img">
</i> 
 <span class="menu-text">Schedule a call w/Prof.&nbsp;Helveston</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false"><i class="bi bi-question-circle-fill" role="img">
</i> 
 <span class="menu-text">Other</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./about.html" class="sidebar-item-text sidebar-link"><i class="bi bi-question-circle-fill" role="img">
</i> 
 <span class="menu-text">About</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./LICENSE.html" class="sidebar-item-text sidebar-link"><i class="bi bi-award-fill" role="img">
</i> 
 <span class="menu-text">License</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="mailto:jph@gwu.edu" class="sidebar-item-text sidebar-link"><i class="bi bi-envelope-fill" role="img">
</i> 
 <span class="menu-text">Contact</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://github.com/emse-madd-gwu/2026-Fall" class="sidebar-item-text sidebar-link"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text">Source files</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#course-information" id="toc-course-information" class="nav-link active" data-scroll-target="#course-information">Course Information</a>
  <ul class="collapse">
  <li><a href="#course-description" id="toc-course-description" class="nav-link" data-scroll-target="#course-description">Course Description</a></li>
  <li><a href="#prerequisites" id="toc-prerequisites" class="nav-link" data-scroll-target="#prerequisites">Prerequisites</a></li>
  </ul></li>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link" data-scroll-target="#learning-objectives">Learning Objectives</a>
  <ul class="collapse">
  <li><a href="#pep-talk" id="toc-pep-talk" class="nav-link" data-scroll-target="#pep-talk">Pep Talk!</a></li>
  </ul></li>
  <li><a href="#required-texts-materials" id="toc-required-texts-materials" class="nav-link" data-scroll-target="#required-texts-materials">Required Texts &amp; Materials</a>
  <ul class="collapse">
  <li><a href="#software" id="toc-software" class="nav-link" data-scroll-target="#software">Software</a></li>
  <li><a href="#textbooks" id="toc-textbooks" class="nav-link" data-scroll-target="#textbooks">Textbooks</a></li>
  </ul></li>
  <li><a href="#assignments" id="toc-assignments" class="nav-link" data-scroll-target="#assignments">Assignments</a>
  <ul class="collapse">
  <li><a href="#participation-attendance" id="toc-participation-attendance" class="nav-link" data-scroll-target="#participation-attendance">Participation &amp; Attendance</a></li>
  <li><a href="#quizzes" id="toc-quizzes" class="nav-link" data-scroll-target="#quizzes">Quizzes</a></li>
  <li><a href="#homework" id="toc-homework" class="nav-link" data-scroll-target="#homework">Homework</a></li>
  <li><a href="#final-project" id="toc-final-project" class="nav-link" data-scroll-target="#final-project">Final Project</a></li>
  <li><a href="#final-exam" id="toc-final-exam" class="nav-link" data-scroll-target="#final-exam">Final Exam</a></li>
  </ul></li>
  <li><a href="#grading" id="toc-grading" class="nav-link" data-scroll-target="#grading">Grading</a>
  <ul class="collapse">
  <li><a href="#category-breakdown" id="toc-category-breakdown" class="nav-link" data-scroll-target="#category-breakdown">Category Breakdown</a></li>
  <li><a href="#grading-scale" id="toc-grading-scale" class="nav-link" data-scroll-target="#grading-scale">Grading Scale</a></li>
  <li><a href="#rounding" id="toc-rounding" class="nav-link" data-scroll-target="#rounding">Rounding</a></li>
  </ul></li>
  <li><a href="#getting-help" id="toc-getting-help" class="nav-link" data-scroll-target="#getting-help">Getting Help</a>
  <ul class="collapse">
  <li><a href="#slack" id="toc-slack" class="nav-link" data-scroll-target="#slack">Slack</a></li>
  <li><a href="#ama-hours" id="toc-ama-hours" class="nav-link" data-scroll-target="#ama-hours">AMA Hours</a></li>
  <li><a href="#tutoring-hours" id="toc-tutoring-hours" class="nav-link" data-scroll-target="#tutoring-hours">Tutoring hours</a></li>
  <li><a href="#library-services" id="toc-library-services" class="nav-link" data-scroll-target="#library-services">Library Services</a></li>
  </ul></li>
  <li><a href="#course-policies" id="toc-course-policies" class="nav-link" data-scroll-target="#course-policies">Course Policies</a>
  <ul class="collapse">
  <li><a href="#tldr" id="toc-tldr" class="nav-link" data-scroll-target="#tldr">tl;dr</a></li>
  <li><a href="#late-policy" id="toc-late-policy" class="nav-link" data-scroll-target="#late-policy">Late Policy</a></li>
  <li><a href="#use-of-chatgpt-and-other-ai-tools" id="toc-use-of-chatgpt-and-other-ai-tools" class="nav-link" data-scroll-target="#use-of-chatgpt-and-other-ai-tools">Use of chatGPT and other AI tools</a></li>
  <li><a href="#cheating" id="toc-cheating" class="nav-link" data-scroll-target="#cheating">Cheating</a>
  <ul class="collapse">
  <li><a href="#penalties" id="toc-penalties" class="nav-link" data-scroll-target="#penalties">Penalties</a></li>
  <li><a href="#grace-period" id="toc-grace-period" class="nav-link" data-scroll-target="#grace-period">Grace Period</a></li>
  </ul></li>
  <li><a href="#children-in-class" id="toc-children-in-class" class="nav-link" data-scroll-target="#children-in-class">Children in class</a></li>
  <li><a href="#laurens-promise" id="toc-laurens-promise" class="nav-link" data-scroll-target="#laurens-promise">Lauren’s Promise</a></li>
  <li><a href="#use-of-course-materials" id="toc-use-of-course-materials" class="nav-link" data-scroll-target="#use-of-course-materials">Use of Course Materials</a></li>
  <li><a href="#recording-in-class" id="toc-recording-in-class" class="nav-link" data-scroll-target="#recording-in-class">Recording in Class</a></li>
  <li><a href="#what-to-do-if-the-instructor-does-not-arrive" id="toc-what-to-do-if-the-instructor-does-not-arrive" class="nav-link" data-scroll-target="#what-to-do-if-the-instructor-does-not-arrive">What To Do if the Instructor Does Not Arrive</a></li>
  </ul></li>
  <li><a href="#university-policies" id="toc-university-policies" class="nav-link" data-scroll-target="#university-policies">University Policies</a>
  <ul class="collapse">
  <li><a href="#university-policy-on-religious-holidays" id="toc-university-policy-on-religious-holidays" class="nav-link" data-scroll-target="#university-policy-on-religious-holidays">University Policy on Religious Holidays</a></li>
  <li><a href="#support-for-students-outside-the-classroom" id="toc-support-for-students-outside-the-classroom" class="nav-link" data-scroll-target="#support-for-students-outside-the-classroom">Support for Students Outside the Classroom</a></li>
  <li><a href="#academic-integrity-code" id="toc-academic-integrity-code" class="nav-link" data-scroll-target="#academic-integrity-code">Academic Integrity Code</a></li>
  </ul></li>
  <li><a href="#super-heros" id="toc-super-heros" class="nav-link" data-scroll-target="#super-heros">Super Heros</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/emse-madd-gwu/2026-Fall/edit/main/syllabus.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/emse-madd-gwu/2026-Fall/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Syllabus</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="course-information" class="level1">
<h1>Course Information</h1>
<div style="width:600px">
<table class="table">
<thead>
<tr class="header">
<th>Instructor</th>
<th>Course</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><i class="bi-person-fill"></i> John Paul Helveston</td>
<td><i class="bi-calendar-fill"></i> Wednesdays</td>
</tr>
<tr class="even">
<td><i class="bi-building-fill"></i> Science &amp; Engineering Hall, 2830</td>
<td><i class="bi-geo-alt-fill"></i> <a href="https://it.gwu.edu/classroom-search/tompkins-hall-201">Tompkins 201</a></td>
</tr>
<tr class="odd">
<td><i class="bi-telephone-fill"></i> +1 (202) 994-7173</td>
<td><i class="bi-calendar-week-fill"></i> Aug.&nbsp;26 - Dec 9, 2026</td>
</tr>
<tr class="even">
<td><i class="bi-envelope-fill"></i> <a href="mailto:jph@gwu.edu">jph@gwu.edu</a></td>
<td><i class="bi-clock-fill"></i> 3:30PM - 6:00PM EST</td>
</tr>
<tr class="odd">
<td><i class="fa fa-brands fa-bluesky"></i> <a href="https://bsky.app/profile/jhelvy.bsky.social">@jhelvy.bsky.social</a></td>
<td><i class="bi-slack"></i> <a href="https://emse-madd-f26.slack.com" target="_blank">Slack</a></td>
</tr>
</tbody>
</table>
</div>
<section id="course-description" class="level2">
<h2 class="anchored" data-anchor-id="course-description">Course Description</h2>
<p>This course provides students with data analysis techniques to inform design decisions in an uncertain, competitive market; topics include consumer choice modeling, programming in the <a href="https://www.r-project.org/">R programming language</a>, survey design, conjoint analysis, optimization, market simulation, and professional communication skills. Over the course of the semester, students will learn and apply theory and methods to a team project to assess the market competitiveness of an emerging product / technology and use marketing analytics to generate design insights. All analyses will be conducted to support reproducibility from raw data to results using <a href="https://quarto.org/">Quarto</a> (which is built on the ideas of <a href="https://bookdown.org/yihui/rmarkdown/">RMarkdown</a>). At the end of the semester, students will submit a final, reproducible report of their project along with a presentation of their findings. This course has a “flipped” classroom structure. Students will spend the majority of class time working through guiding practice exercises or working on their projects. To prepare for class, students must complete weekly assignments that involve watching and reviewing recorded lecture materials and answering related practice questions.</p>
</section>
<section id="prerequisites" class="level2">
<h2 class="anchored" data-anchor-id="prerequisites">Prerequisites</h2>
<p>This course requires prior exposure to:</p>
<ul>
<li>Probability theory</li>
<li>Multivariable calculus</li>
<li>Linear algebra</li>
<li>Regression</li>
</ul>
<p>Each of these concepts will be applied throughout the course, and no time will be spent reviewing the foundational elements of each concept.</p>
<p>In addition, we will work in the <a href="https://www.r-project.org/">R programming language</a> throughout the course, but no prior programming experience is required. We will spend the first three weeks going through exercises to get up to speed in R.</p>
<p>Students are encouraged to complete <a href="./self-assessment.html">this self assessment</a> prior to registering for the course to self-assess familiarity with these concepts.</p>
</section>
</section>
<section id="learning-objectives" class="level1">
<h1>Learning Objectives</h1>
<p>Having successfully completed this course, students will be able to:</p>
<ul>
<li>Import, wrangle, visualize, and export data in R.</li>
<li>Design surveys to obtain informative data about consumer preferences for product features.</li>
<li>Build and estimate discrete choice models.</li>
<li>Analyze consumer choice data to estimate consumer preferences for product features.</li>
<li>Design and create effective charts and presentations.</li>
<li>Communicate results in terms of design insights.</li>
</ul>
<section id="pep-talk" class="level2">
<h2 class="anchored" data-anchor-id="pep-talk">Pep Talk!</h2>
<p>Working in and learning a programming language can be as challenging as learning a new spoken language. Hadley Wickham (chief data scientist at RStudio and author of many amazing R packages you’ll be using) <a href="https://r-posts.com/advice-to-young-and-old-programmers-a-conversation-with-hadley-wickham/">made this wise observation</a>:</p>
<blockquote class="blockquote">
<p>It’s easy when you start out programming to get really frustrated and think, “Oh it’s me, I’m really stupid,” or, “I’m not made out to program.” But, that is absolutely not the case. Everyone gets frustrated. I still get frustrated occasionally when writing R code. It’s just a natural part of programming. So, it happens to everyone and gets less and less over time. Don’t blame yourself. Just take a break, do something fun, and then come back and try again later.</p>
</blockquote>
<p>If you’re finding yourself taking way too long hitting your head against a wall and not understanding, <strong>take a break</strong>, talk to classmates, ask questions in Slack, and try it again later.</p>
<p><strong>I promise, you can do this!</strong></p>
</section>
</section>
<section id="required-texts-materials" class="level1">
<h1>Required Texts &amp; Materials</h1>
<p>All texts and software for this course is freely available on the web, accessible from this website.</p>
<section id="software" class="level2">
<h2 class="anchored" data-anchor-id="software">Software</h2>
<p>Go to the Course <a href="./software.html">Software page</a> for detailed instructions on how to install the software we’ll be using. Here’s a quick list:</p>
<ul>
<li>R (version 4.1.0 or later), which can be downloaded from <a href="https://cloud.r-project.org">The Comprehensive R Archive Network (CRAN)</a></li>
<li>RStudio (Desktop Version), a free IDE for R, which can be downloaded from <a href="https://rstudio.com/products/rstudio/download/">RStudio</a></li>
<li>We’ll be using <a href="https://emse-madd-f26.slack.com" target="_blank">Slack</a> for most communication.</li>
</ul>
</section>
<section id="textbooks" class="level2">
<h2 class="anchored" data-anchor-id="textbooks">Textbooks</h2>
<ul>
<li>For learning the basics of R, I recommend referencing my book “Programming for Analytics in R”, by Professor Helveston. The book is available freely on the web at <a href="https://p4a.jhelvy.com/" target="_blank">https://p4a.jhelvy.com/</a>.</li>
<li>The theoretical underpinnings to most of the modeling we will do in this course can be found in the book “Discrete Choice Methods with Simulation” by Dr.&nbsp;Kenneth Train. The book is available freely on the web at <a href="https://eml.berkeley.edu/books/choice2.html" target="_blank">https://eml.berkeley.edu/books/choice2.html</a>.</li>
</ul>
</section>
</section>
<section id="assignments" class="level1">
<h1>Assignments</h1>
<section id="participation-attendance" class="level2">
<h2 class="anchored" data-anchor-id="participation-attendance">Participation &amp; Attendance</h2>
<p><strong>Attendance will be taken</strong> and will be part of your participation grade.</p>
<p>In-person attendance is critical as we will spend a lot of time working on problems and writing code during class. You should plan to attend class in person each week.</p>
<p><strong>There will be no option for remote attendance (e.g.&nbsp;zoom)</strong>, and class sessions will not be recorded. If you have any questions or need special accommodations, send me a message on slack and we can discuss. If you must miss class for an excused absence (e.g.&nbsp;medical issue), please message Professor Helveston and get notes from your fellows classmates.</p>
<p>Multiple absences, inappropriate or unprofessional behavior during class (such as monopolizing discussions or being rude or disruptive), not participating in classroom exercises, and not being prepared for class will result in a poor score for attendance and participation.</p>
</section>
<section id="quizzes" class="level2">
<h2 class="anchored" data-anchor-id="quizzes">Quizzes</h2>
<p>Quizzes will be given about once every other week immediately at the beginning of class (check the <a href="schedule.html">schedule</a>). Make up quizzes will not be available if you miss it (except for excused absences). Please show up on time to class each week to ensure that you do not miss a quiz. Quizzes will cover material presented in previous classes and assignments during the weeks since the most-recent quiz.</p>
<p>Quizzes are <strong>short</strong> (10 minutes) and are designed to test for fluency and to demonstrate where additional study is needed. <strong>Quizzes are low-stakes</strong> - your worst one is dropped, and the rest count for a small portion of your final grade. If you do poorly on one or two, use that as feedback on where you need additional improvement.</p>
<blockquote class="blockquote">
<p><strong>Why quiz at all?</strong> Research shows that giving small quizzes throughout a class can dramatically help with <em>retention</em>. It’s a phenomenon known as the “retrieval effect” - basically, you have to <em>practice</em> remembering things, otherwise your brain won’t remember them. The phenomenon and research on it is explained in detail in the book <a href="https://www.hup.harvard.edu/catalog.php?isbn=9780674729018">“Make It Stick: The Science of Successful Learning,”</a> by Brown, Roediger, and McDaniel.</p>
</blockquote>
</section>
<section id="homework" class="level2">
<h2 class="anchored" data-anchor-id="homework">Homework</h2>
<p>Each week, students will be assigned readings and exercises to prepare for the next class period. Students will need to submit reflections on these readings each week, which may involve answering some practice questions. These are graded using a check system:</p>
<ul>
<li>✔+ (110%): Responses shows phenomenal thought and engagement with the course content. I will not assign these often.</li>
<li>✔ (100%): Responses are thoughtful, well-written, and show engagement with the course content. This is the expected level of performance.</li>
<li>✔− (50%): Responses are hastily composed, too short, and/or only cursorily engages with the course content. This grade signals that you need to improve next time. I will <em>hopefully</em> not assign these often.</li>
</ul>
<p>Notice that this is essentially a pass/fail system. I’m not grading your writing ability and I’m not counting the number of words you write. I’m looking for thoughtful engagement, that’s all.</p>
</section>
<section id="final-project" class="level2">
<h2 class="anchored" data-anchor-id="final-project">Final Project</h2>
<p>Throughout the semester, students will work in teams of 3-4 students towards a final project. The project is broken into multiple phases with key deliverables due throughout the semester. See the <a href="./project/0-overview.html">Project Overview</a> page for more details.</p>
</section>
<section id="final-exam" class="level2">
<h2 class="anchored" data-anchor-id="final-exam">Final Exam</h2>
<p>The final exam is a take-home exam, and we will spend a portion of the last day of class going over the solutions together.</p>
</section>
</section>
<section id="grading" class="level1">
<h1>Grading</h1>
<section id="category-breakdown" class="level2">
<h2 class="anchored" data-anchor-id="category-breakdown">Category Breakdown</h2>
<p>Final grades will be calculated as follows:</p>
<div style="width:550px">
<table class="table">
<thead>
<tr class="header">
<th>Item</th>
<th>Weight</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Participation / Attendance</td>
<td>5%</td>
<td>(Yes, I take attendance)</td>
</tr>
<tr class="even">
<td>Reflections (11)</td>
<td>30 %</td>
<td>Weekly assignment (10 x 3%), lowest 1 dropped</td>
</tr>
<tr class="odd">
<td>Quizzes (5)</td>
<td>10 %</td>
<td>Lowest 1 dropped</td>
</tr>
<tr class="even">
<td>Final Exam</td>
<td>10 %</td>
<td>Take home exam</td>
</tr>
<tr class="odd">
<td>Project Proposal</td>
<td>5 %</td>
<td>Teams of 3-4 students</td>
</tr>
<tr class="even">
<td>Survey Plan</td>
<td>5 %</td>
<td></td>
</tr>
<tr class="odd">
<td>Pilot Survey</td>
<td>5 %</td>
<td></td>
</tr>
<tr class="even">
<td>Pilot Analysis</td>
<td>5 %</td>
<td></td>
</tr>
<tr class="odd">
<td>Final Survey</td>
<td>5 %</td>
<td></td>
</tr>
<tr class="even">
<td>Final Analysis Report</td>
<td>15 %</td>
<td></td>
</tr>
<tr class="odd">
<td>Final Presentation</td>
<td>5 %</td>
<td></td>
</tr>
</tbody>
</table>
</div>
<p>Here’s a visual breakdown by category:</p>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="figs/grade-breakdown-1.png" class="img-fluid quarto-figure quarto-figure-left figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="grading-scale" class="level2">
<h2 class="anchored" data-anchor-id="grading-scale">Grading Scale</h2>
<div style="width:400px">
<table class="table">
<thead>
<tr class="header">
<th>Grade</th>
<th>Range</th>
<th>Grade</th>
<th>Range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>94 - 100%</td>
<td>C</td>
<td>74 - 76.99%</td>
</tr>
<tr class="even">
<td>A-</td>
<td>90 - 93.99%</td>
<td>C-</td>
<td>70 - 73.99%</td>
</tr>
<tr class="odd">
<td>B+</td>
<td>87 - 89.99%</td>
<td>D+</td>
<td>67 - 69.99%</td>
</tr>
<tr class="even">
<td>B</td>
<td>84 - 86.99%</td>
<td>D</td>
<td>64 - 66.99%</td>
</tr>
<tr class="odd">
<td>B-</td>
<td>80 - 83.99%</td>
<td>D-</td>
<td>60 - 63.99%</td>
</tr>
<tr class="even">
<td>C+</td>
<td>77 - 79.99%</td>
<td>F</td>
<td>&lt; 60%</td>
</tr>
</tbody>
</table>
</div>
<p>The course instructors may choose to change the scales at their discretion. You are guaranteed that your letter grade will never become worse as a result of changing scales.</p>
</section>
<section id="rounding" class="level2">
<h2 class="anchored" data-anchor-id="rounding">Rounding</h2>
<p><strong>I do not round final grades</strong>. Here’s why. Wherever the line is drawn, there will always be students just below or just above, and rounding will only move that bar and create another group of students who are just below and just above. Rounding does not eliminate the issue but rather just shifts it to another group of students. This is why I draw the lines before the course starts - to ensure a fair and transparent system for everyone, that way you don’t have to shoot for a moving bar. To be clear, this means I will not modify or round your final score, even if you’re <em>very close</em> to a different letter grade (e.g., a 93.98 is an “A-” and will not be rounded up to an “A”).</p>
<p>Rather than round, I grade generously throughout the semester. For example, if you give a quiz your best shot and completely fail it, you will likely get a 50% instead of a 0%. The 50% is for trying as learning still happens when you try regardless if you get the question correct (0s are reserved for those who simply don’t attempt it).</p>
</section>
</section>
<section id="getting-help" class="level1">
<h1>Getting Help</h1>
<p>This class can be challenging - <strong>do not suffer in silence!</strong> We have lots of ways to get help.</p>
<section id="slack" class="level2">
<h2 class="anchored" data-anchor-id="slack">Slack</h2>
<p>All course communication will be managed through <a href="https://emse-madd-f26.slack.com" target="_blank">Slack</a>. A link to sign up for the course slack page can be found on the one (and only) announcement on Blackboard.</p>
<p><strong>You can use Slack to</strong>:</p>
<ul>
<li>Ask general questions.</li>
<li>Ask for help with an assignment.</li>
<li>Send direct, private messages to each other or the instructors (just like email…but better!)</li>
</ul>
<blockquote class="blockquote">
<p><strong>Asking for help on Slack</strong>: You can post questions on slack and receive quick responses. This also enables other students to see answers to common questions. Be specific - if your code has an error you don’t understand, <strong>include the code and the error message</strong> in your question.</p>
</blockquote>
</section>
<section id="ama-hours" class="level2">
<h2 class="anchored" data-anchor-id="ama-hours">AMA Hours</h2>
<p>I will hold regular “Ask Me Anything” hours each week. The specific hours will be posted on the course slack. During this period, you can come to my office (SEH 2830) and ask me anything. And I mean anything. Most of the time you may just have a question related to class, but I am also happy to discuss anything else with you regarding life, important decisions, career, art, music, dance, etc.</p>
<p>If the AMA hours don’t work with your schedule, you can always schedule a zoom call with me using <a href="https://jhelvy.appointlet.com/b/professor-helveston">this link</a>. I’m available most days of the week.</p>
</section>
<section id="tutoring-hours" class="level2">
<h2 class="anchored" data-anchor-id="tutoring-hours">Tutoring hours</h2>
<p>Your class tutors will each hold a dedicated period of time each week for zoom tutoring hours. Please don’t make your tutors sit and do emails for two hours - come by and ask for help!</p>
</section>
<section id="library-services" class="level2">
<h2 class="anchored" data-anchor-id="library-services">Library Services</h2>
<p>While the University Library is not a stand in for TAs, you can schedule a consultation for general help with Coding, Programming, Data, Statistical, and GIS. See more at https://academiccommons.gwu.edu/writing-research-help</p>
</section>
</section>
<section id="course-policies" class="level1">
<h1>Course Policies</h1>
<section id="tldr" class="level2">
<h2 class="anchored" data-anchor-id="tldr">tl;dr</h2>
<ul>
<li>BE NICE</li>
<li>BE ON TIME</li>
<li>BE HONEST</li>
<li>DON’T CHEAT</li>
<li>SERIOUSLY: DON’T CHEAT</li>
</ul>
</section>
<section id="late-policy" class="level2">
<h2 class="anchored" data-anchor-id="late-policy">Late Policy</h2>
<p>Each students is allowed <strong>3</strong> late homework submission days - use them however you want, no questions asked. These are meant to cover illness, family emergencies, and religious holidays.</p>
<p>Beyond those, assignments are due by 11:59pm on the assigned due date unless specified otherwise. Assignments submitted up to 24 hours past this deadline will be graded to a max of 50% of the available points. Assignments submitted beyond 24 hours past the deadline will not be graded and will be assigned a 0.</p>
<p>If you need a special accommodation such as due to an illness, family emergency, or religious holidays, contact the instructor ahead of time.</p>
</section>
<section id="use-of-chatgpt-and-other-ai-tools" class="level2">
<h2 class="anchored" data-anchor-id="use-of-chatgpt-and-other-ai-tools">Use of chatGPT and other AI tools</h2>
<p>Use of large language models (LLMs) like chatGPT, Claude, etc. are not only permitted but encouraged. You need to learn how to use AI tools to learn new skills, improve productivity, and find solutions.</p>
<p>While LLMs are pretty good, sometimes they suck. <strong>Don’t blindly trust them</strong> - they will betray you, especially with code.</p>
<p>I will grade AI generated work no differently than work you produce without AI. But it’s important that you understand <strong>your work should not suck.</strong> Sometimes AI-generated work <em>really</em>, <em>really</em> sucks, so if you blindly trust an AI to do your work and submit it and it sucks, you may not like the grade.</p>
<p>Here are some tips on how to work with AI tools but not generate work that sucks:</p>
<ul>
<li>Don’t submit code that doesn’t run (actually run it before submitting it).</li>
<li>Actually read what the AI generates.</li>
<li>Don’t use methods I don’t teach. There are dozens of ways to do things - <strong>you should use the approach I teach</strong>. Using some other approach that an AI generates is a <em>very bad</em> idea.</li>
</ul>
<p>Your goal in using tools like ChatGPT should be to see them as an assistant - a tool to help you accomplish the task - rather than as a solutions manual. Take the time to work through the code / text these tools generate and ensure that what they provide is accurate, and if not make the corrections to fix their mistakes.</p>
<blockquote class="blockquote">
<p>Curious how LLMs actually work? Check out <a href="https://www.understandingai.org/p/large-language-models-explained-with">this article</a>, which provides a simplified description of how they work (which itself is still quite complicated).</p>
</blockquote>
</section>
<section id="cheating" class="level2">
<h2 class="anchored" data-anchor-id="cheating">Cheating</h2>
<p>Cheating results in a penalty on the first offense, and failing the course on the second offense. Cheating on assignments can include:</p>
<ul>
<li>Copying or stealing any amount of code from someone currently in the class or someone who has taken the class before.</li>
<li>NOTE: Copying is never okay, whether the code is provided electronically, visually, audibly, or on paper. Even if you work together on an assignment, <strong>write your own code</strong>.</li>
<li>Providing code you have written for an assignment to anyone else in the class.</li>
<li>Putting code solutions from the course assignments online.</li>
<li>Receiving code-level assistance from any person not associated with the course.</li>
<li>Getting someone else to write the assignment code for you.</li>
<li>Asking questions about the assignments on any online services outside of the course office hours / Slack.</li>
</ul>
<p>Cheating on quizzes, assignments, or the final project can include:</p>
<ul>
<li>Referring to any external resources while completing the assignment (phones, notes, etc.).</li>
<li>Copying part of an answer off of another student’s paper, even if it is very small.</li>
<li>Using solutions provided by students who previously took the course.</li>
</ul>
<section id="penalties" class="level3">
<h3 class="anchored" data-anchor-id="penalties">Penalties</h3>
<p>Violations will be reported to the <a href="https://studentconduct.gwu.edu/charging-academic-integrity-violations">Office of Student Rights &amp; Responsibilities</a>. Penalties are decided by the course instructors, and can vary based on the severity of the offense. Possible penalties include:</p>
<ul>
<li>Receiving a 0 on the assignment/quiz in question.</li>
<li>Receiving a full letter grade deduction in the course.</li>
<li>Automatically failing the course.</li>
</ul>
<p>Depending on the student’s prior academic history, violations may also be accompanied by a letter to the Dean of Student Affairs, again at the instructors’ discretion. This can lead to university-level penalties, such as being suspended or expelled.</p>
</section>
<section id="grace-period" class="level3">
<h3 class="anchored" data-anchor-id="grace-period">Grace Period</h3>
<p>College is a time when you do a lot of learning. Sometimes, you might make bad decisions or mistakes. The most important thing for you to do is to learn from your mistakes, to constantly grow, and become a better person.</p>
<p>Sometimes, students panic and copy code right before the deadline, then regret what they did afterwards. Therefore, you may rescind any homework submission for up to 24 hours after the deadline with no questions asked. Simply email the course instructors asking to delete the submission in question, and we will do so. Deleted submissions will not be considered during plagiarism detection, though of course they will also not be graded. However, it will always be better to get a 0 (or partial credit) on an assignment than to get a cheating violation!</p>
</section>
</section>
<section id="children-in-class" class="level2">
<h2 class="anchored" data-anchor-id="children-in-class">Children in class</h2>
<!-- Policy copied from Andrew Heiss's class -->
<!-- https://evalsp20.classes.andrewheiss.com/syllabus/ -->
<p>I applaud all of you who attend school with children! It is difficult to balance academic, work, and family commitments, and I want you to succeed. Here are my policies regarding children in class:</p>
<ol type="1">
<li>All breastfeeding babies are welcome in class as often as necessary.</li>
<li>Non-nursing babies and older children are welcome whenever alternate arrangements cannot be made. As a parent of young children, I understand that babysitters fall through, partners have conflicting schedules, children get sick, and other issues arise that leave parents with few other options.</li>
<li>In cases where children come to class, I invite parents/caregivers to sit close to the door so as to more easily excuse yourself to attend to your child’s needs. Non-parents in the class: please reserve seats near the door for your parenting classmates.</li>
<li>All students are expected to join with me in creating a welcoming environment that is respectful of your classmates who bring children to class.</li>
</ol>
<p>I understand that sleep deprivation and exhaustion are among the most difficult aspects of parenting young children. The struggle of balancing school, work, childcare, and graduate school is tiring, and I will do my best to accommodate any such issues while maintaining the same high expectations for all students enrolled in the class. Please do not hesitate to contact me with any questions or concerns.</p>
</section>
<section id="laurens-promise" class="level2">
<h2 class="anchored" data-anchor-id="laurens-promise">Lauren’s Promise</h2>
<!-- Policy copied from Andrew Heiss's class -->
<!-- https://evalsp20.classes.andrewheiss.com/syllabus/ -->
<p><strong>I will listen and believe you if someone is threatening you.</strong></p>
<p>Lauren McCluskey, a 21-year-old honors student athlete, <a href="https://www.sltrib.com/opinion/commentary/2019/02/10/commentary-failing-lauren/">was murdered on October 22, 2018 by a man she briefly dated on the University of Utah campus</a>. We must all take action to ensure that this never happens again.</p>
<p>If you are in immediate danger, call 911 or GWU police at 202-994-6111 (GWPD).</p>
<p>If you are experiencing sexual assault, domestic violence, or stalking, if you report it to me I will listen and connect you to resources or call GWU’s <a href="https://healthcenter.gwu.edu/counseling-and-psychological-services">Counseling and Psychological Services</a> (202-994-5300).</p>
<p>Any form of sexual harassment or violence will not be excused or tolerated at GWU. GWU has instituted procedures to respond to violations of these laws and standards, programs aimed at the prevention of such conduct, and intervention on behalf of the victims. GWU Police officers will treat victims of sexual assault, domestic violence, and stalking with respect and dignity. Advocates on campus and in the community can help with victims’ physical and emotional health, reporting options, and academic concerns.</p>
</section>
<section id="use-of-course-materials" class="level2">
<h2 class="anchored" data-anchor-id="use-of-course-materials">Use of Course Materials</h2>
<p>All course materials available on the course website are developed open source - you are welcome to post and share them following the licensing guidelines listed in the <a href="./LICENSE.html">license</a> page.</p>
<p>However, all <strong>solutions</strong> to assignments and quizzes are proprietary. Don’t post them online or try to sell them - this is a violation of the <a href="https://studentconduct.gwu.edu/code-student-conduct">student code of conduct</a> and it is also a violation of the class cheating policy.</p>
</section>
<section id="recording-in-class" class="level2">
<h2 class="anchored" data-anchor-id="recording-in-class">Recording in Class</h2>
<p>You are free to record class periods (audio and / or video) for your own personal study use and only for your personal study use. If you do record a class period, you are prohibited from posting or sharing the content online or with others.</p>
</section>
<section id="what-to-do-if-the-instructor-does-not-arrive" class="level2">
<h2 class="anchored" data-anchor-id="what-to-do-if-the-instructor-does-not-arrive">What To Do if the Instructor Does Not Arrive</h2>
<p>Wait <strong>20 minutes</strong>, after that you’re free to leave. One member of the class should be selected to notify the EMSE Department of the Instructor’s absence by calling the EMSE Department 202-994-4892 on next business day.</p>
</section>
</section>
<section id="university-policies" class="level1">
<h1>University Policies</h1>
<section id="university-policy-on-religious-holidays" class="level2">
<h2 class="anchored" data-anchor-id="university-policy-on-religious-holidays">University Policy on Religious Holidays</h2>
<p>In accordance with University Policy, students should notify faculty during the first week of the semester of their intention to be absent from class on their day(s) of religious observance. Official university policy here: https://students.gwu.edu/accommodations-religious-holidays</p>
<ul>
<li>Students should notify faculty during the first week of the semester of their intention to be absent from class on their day(s) of religious observance.</li>
<li>Faculty should extend to these students the courtesy of absence without penalty on such occasions, including permission to make up examinations.</li>
<li>Faculty who intend to observe a religious holiday should arrange at the beginning of the semester to reschedule missed classes or to make other provisions for their course-related activities.</li>
</ul>
</section>
<section id="support-for-students-outside-the-classroom" class="level2">
<h2 class="anchored" data-anchor-id="support-for-students-outside-the-classroom">Support for Students Outside the Classroom</h2>
<p><strong>Disability Support Services (DSS)</strong>: Any student who may need an accommodation based on the potential impact of a disability should contact the Disability Support Services office at 202-994-8250 in the Rome Hall, Suite 102, to establish eligibility and to coordinate reasonable accommodations. For additional information please refer to: https://disabilitysupport.gwu.edu/</p>
<p><strong>Mental Health Services (202-994-5300)</strong>: The University’s Mental Health Services offers 24/7 assistance and referral to address students’ personal, social, career, and study skills problems. Services for students include: crisis and emergency mental health consultations confidential assessment, counseling services (individual and small group), and referrals. https://healthcenter.gwu.edu/counseling-and-psychological-services</p>
</section>
<section id="academic-integrity-code" class="level2">
<h2 class="anchored" data-anchor-id="academic-integrity-code">Academic Integrity Code</h2>
<p>Academic dishonesty is defined as cheating of any kind, including misrepresenting one’s own work, taking credit for the work of others without crediting them and without appropriate authorization, and the fabrication of information. For the remainder of the code, see: https://studentconduct.gwu.edu/code-academic-integrity</p>
<p>In addition to the formal code of academic integrity, the instructor expects that students will treat this course with the level of professionalism required in the workplace. Remember that real firms are sponsoring student projects throughout the semester; in a workplace setting, these firms would be paying clients for the analyses being conducted. This course prepares students to succeed in the workplace, and maintaining a high degree of professionalism is expected.</p>
</section>
</section>
<section id="super-heros" class="level1">
<h1>Super Heros</h1>
<div class="grid">
<div class="g-col-4">
<p><img src="images/prof_x.gif" width="100%"></p>
</div>
<div class="g-col-8">
<p>Once you have read this entire syllabus and viewed the <a href="./schedule.html">course schedule</a>, post a picture of your favorite super hero in the welcome channel in Slack.</p>
<p>For real.</p>
<p>Brownie points if it’s animated.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/madd\.seas\.gwu\.edu\/2026-Fall\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 © 2026 John Paul Helveston  <a href="LICENSE.html"><i class="fab fa-creative-commons"></i><i class="fab fa-creative-commons-by"></i><i class="fab fa-creative-commons-sa"></i></a><br><i class="far fa-calendar-alt"></i> Wednesdays | <i class="far fa-clock"></i> 3:30PM - 6:00PM EST | <a href="https://it.gwu.edu/classroom-search/tompkins-hall-201"><i class="fa fa-map-marker-alt"></i> Tompkins 201</a><br><a href="https://www.jhelvy.com"><i class="fas fa-user"></i> Dr. John Paul Helveston</a> | <a href="mailto:jph@gwu.edu"><i class="fas fa-envelope"></i> jph@gwu.edu</a> | <a href="https://github.com/emse-madd-gwu/2026-Fall"><i class="fab fa-github"></i></a>
  </li>  
</ul>
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/emse-madd-gwu/2026-Fall/edit/main/syllabus.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/emse-madd-gwu/2026-Fall/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>