```{r}
#| include: false

source(here::here("_common.R"))

due <- get_schedule() %>%
  filter(n_assign == params$number) %>%
  pull(due_assign) %>%
  paste0(" by 11:59pm")

url_template <- paste0(
  'https://madd.seas.gwu.edu/2026-Fall/templates/hw',
  params$number, '.zip')

hw_file <- paste0('hw', params$number, '.qmd')
```

> **Due**: `r due`
>
> **Weight**: This assignment is worth 2.5% of your final grade.
>
> **Purpose**: `r params$purpose`
>
> **Submit**: Commit and push your completed assignment to your course GitHub repository (see the "Submit" section at the end of this assignment).
>
> **Assessment**: This assignment is graded using a check system:
>
> - ✔+ (110%): Responses shows phenomenal thought and engagement with the course content. I will not assign these often.
> - ✔ (100%): Responses are thoughtful, well-written, and show engagement with the course content. This is the expected level of performance.
> - ✔− (50%): Responses are hastily composed, too short, and/or only cursorily engages with the course content. This grade signals that you need to improve next time. I will _hopefully_ not assign these often.
>
> Notice that this is essentially a pass/fail system. I'm not grading your writing ability and I'm not counting the number of words you write - I'm looking for thoughtful engagement. One or two sentences is **not enough**. Write at least a paragraph and show me that you did the readings assigned.
