---
title: "Quarto & Plotting"
params:
  number: 3
  purpose: 'The purpose of this assignment is to get familiar with creating plots using the ggplot2 library and to introduce you to the "Quarto" file format.'
---

```{r child = here::here("fragments", "hw.qmd")}
```

# 1. Get Organized

Follow these instructions:

1. Download and edit [this template](`r url_template`).
2. Unzip the template folder. **Make sure you actually unzip it**! (in Windows, right-click it and use "extract all")
3. Open the .Rproj file to open RStudio.
4. Inside RStudio, open the ``r hw_file`` file, take notes, and write some example code as you go through the readings / exercises below.

> Notice that this week's template is a `.qmd` file, which is called a "Quarto Markdown" file (or just "Quarto" file). You'll learn about what these files are and how they are different from .R files in the readings for this week. From now on, we'll mostly be using Quarto files for our assignments (including your project deliverables).

# 2. Readings

Open up a notebook (physical, digital...whatever you take notes in best), and **take notes** while you go through these readings:

1. Lesson [5 "Data Visualization"](https://jhelvy.github.io/r4aPrimer/L5-data-visualization.html)
2. Lesson [6 "Reproducible Reporting"](https://jhelvy.github.io/r4aPrimer/L6-reproducible-reporting.html)

# 3. Exercises

We're going to again look at the Posit ["recipes"](https://posit.cloud/learn/recipes) page for examples on how to implement things in {{< fa brands r-project>}}. This time, focus on the "Visualize Data" section - go through each recipe and try to implement it yourself in your ``r hw_file`` file. We'll spend time in class next week going over ggplot and doing more practice with it.

# 4. Review

Last week you read about working with data in R using the tidyverse and the dplyr package (handing data using pipes, `%>%`, etc.). We also discussed this in class. 

It is very important that you feel comfortable working with data frames using this approach as we will use it throughout the semester. 

For extra practice, take a look at [this assignment](https://p4a.seas.gwu.edu/2025-Spring/hw/9-data-wrangling.html) from my Intro to Programming in R class that I taught in the spring semester. I **strongly** encourage you to look through it and try to answer the questions, especially if this is your first time using the tidyverse and / or R. It is just good practice to review these skills.

# 5. Reflect

Reflect on what you've learned while going through these readings and exercises. Is there anything that jumped out at you? Anything you found particularly interesting or confusing? Write at least a paragraph in your ``r hw_file`` file, and include at least one question. The teaching team will review the questions we get and will try to answer them either in Slack or in class.

If you're unsure where to start with a reflection, try filling out this template:

> "I used to think ______, now I think ______ 🤔"

# 6. Submit

To submit your assignment, follow these instructions:

1. Render your .qmd file by either clicking the "Render" button in RStudio or running the command ``r paste0('quarto::quarto_render("', hw_file, '")')`` command.
2. Open the rendered html file and make sure it looks good! Is all the formatting as you expected?
3. Create a zip file of all the files in your R project folder for this assignment and submit it to your course GitHub repository (GitHub submission details coming soon).
